### PR TITLE
Db implementation

### PR DESCRIPTION
**Pull request by ExtraShotLatte**
Added creation of user documents upon signup. Signing in with google will create the document if the document doesn't exist. 

Things to note:
- Are we updating signup form to include name?
- Need to implement a logout button, i made one as a placeholder for testing, can be easily removed, labelled as "DEBUG: XXX"
- Structure of how the different items are linked together is done, awaiting actual implementation - will be done soon
- Probably some merge conflict, will deconflict

### CODE REVIEW

**Comment by ExtraShotLatte** [comment]
Conflict resolved

**Comment by ExtraShotLatte** [comment]
Hm, probs w the way i deconflicted on the editor

**Comment by ExtraShotLatte** [comment]
Resolved

**Comment by Jnjy** [comment]
- plan to prompt new user to input details after successful sign up (set up their profile)
- logout button has been added in the latest version

The rest looks good to me

**Pull request merged**
